### ISSUE TITLE
Один репозиторий - один проект (ДЗ)

### ISSUE THREAD

**Issue by coursar** [dilyarakhabibullina/homeworkDilyara#1]
Для каждого ДЗ нужно делать свой репозиторий

**Comment by dilyarakhabibullina** [comment]
Хорошо, сделаю, только я в командировке по пятницу, могу к субботе не успеть

**Comment by dilyarakhabibullina** [comment]
Пардон, я же наверное не могу закрыть коммент, пока не разложу домашка по репозиториям?

**Comment by coursar** [comment]
Можете )) но лучше так не делать ))
