### ISSUE TITLE
Ctrl + Alt + L для выравнивания кода

### ISSUE THREAD

**Issue by coursar** [dilyarakhabibullina/homeworkDilyara#3]
https://github.com/dilyarakhabibullina/homeworkDilyara/blob/9332975646ba34a9c55bb171582df4fc46266af8/Wallpaper.java#L1-L14

**Comment by dilyarakhabibullina** [comment]
Это для меня новость. Код должен быть ровненьким?

**Comment by coursar** [comment]
аккуратным и ровным
