### ISSUE TITLE
where can I find .gitignore file?

### ISSUE THREAD

**Issue by dilyarakhabibullina** [dilyarakhabibullina/homeworkDilyara#4]
@courser, я не поняла, где именно я могу скопировать содержимое для файла .gitignore. Напомните пож-та!

**Comment by dilyarakhabibullina** [comment]
@coursar, I've find it inside the Lesson:-).

**Comment by coursar** [comment]
https://gist.github.com/coursar - .gitignore для курса Python (не перепутайте)
